### ISSUE TITLE
Site launch checklist

### ISSUE THREAD

**Issue by zsherman** [timberio/timber-io#23]
- [ ] hook up sign up buttons
- [ ] show link to app.timber.io if you're logged in
- [ ] swap out screenshots
- [x] publish first post
- [x] basic seo tags
- [ ] ssl certs
- [ ] force ssl
- [ ] video
- [ ] finalize plans
- [ ] copy update/runthrough
- [x] install segment
- [ ] add team member descriptions
- [x] change customer logos to real companies
- [ ] publish to timber.io domain
